name: Build Docker images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the ANYK image
        run: docker compose -f anyk/docker-compose.yml build

      - name: Build the ANYK-19HIPA image
        run: docker compose -f anyk-19hipa/docker-compose.yml build

      - name: Build the ANYK-20HIPA image
        run: docker compose -f anyk-20hipa/docker-compose.yml build

      - name: Build the ANYK-21HIPA image
        run: docker compose -f anyk-21hipa/docker-compose.yml build

      - name: Build the ANYK-IGAZOL image
        run: docker compose -f anyk-igazol/docker-compose.yml build

      - name: Build the ANYK-22HIPAK image
        run: docker compose -f anyk-22hipak/docker-compose.yml build

      - name: Build the ANYK-OEPEUCARD image
        run: docker compose -f anyk-oepeucard/docker-compose.yml build
