name: Build Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-base:
    strategy:
      matrix:
        desktop: ["kde", "mate", "xfce"]
        base: ["base"]

    runs-on: ubuntu-latest

    env:
      DESKTOP: ${{ matrix.desktop }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the ${{ matrix.base }} ${{ matrix.desktop }} image
        run: docker buildx bake -f build/${{ matrix.base }}.yml

  list-plugins:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate plugin matrix
        id: generate-matrix
        run: echo "matrix=$(ls build/plugin/*.yml | sed s/"build\/plugin\/"// | sed s/.yml// | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-plugins:
    needs: [build-base, list-plugins]
    strategy:
      matrix:
        desktop: ["kde", "mate", "xfce"]
        plugin: ${{ fromJson(needs.list-plugins.outputs.matrix) }}

    runs-on: ubuntu-latest

    env:
      DESKTOP: ${{ matrix.desktop }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the ${{ matrix.plugin }} ${{ matrix.desktop }} image
        run: docker buildx bake -f build/plugin/${{ matrix.plugin }}.yml
