name: Build and publish Docker images

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-base:
    strategy:
      matrix:
        desktop: ["kde", "mate", "xfce"]
        base: ["base"]

    runs-on: ubuntu-latest

    env:
      DESKTOP: ${{ matrix.desktop }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish the ${{ matrix.base }} ${{ matrix.desktop }} image
        run: docker buildx bake -f build/${{ matrix.base }}.yml --push

  list-plugins:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Generate plugin matrix
        id: generate-matrix
        run: echo "matrix=$(ls build/plugin/*.yml | sed s/"build\/plugin\/"// | sed s/.yml// | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-plugins:
    needs: [build-base, list-plugins]
    strategy:
      matrix:
        desktop: ["kde", "mate", "xfce"]
        plugin: ${{ fromJson(needs.list-plugins.outputs.matrix) }}

    runs-on: ubuntu-latest

    env:
      DESKTOP: ${{ matrix.desktop }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish the ${{ matrix.plugin }} ${{ matrix.desktop }} image
        run: docker buildx bake -f build/plugin/${{ matrix.plugin }}.yml --push

  update-readme:
    needs: [build-base, build-plugins]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: reisingeradam/anyk
          readme-filepath: ./README.en.md
