name: Build and publish Docker images

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-base:
    strategy:
      matrix:
        desktop: ["kde", "mate", "xfce"]
        base: ["base"]

    runs-on: ubuntu-latest

    env:
      DESKTOP: ${{ matrix.desktop }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and publish the ${{ matrix.base }} ${{ matrix.desktop }} image
        uses: docker/bake-action@v2.3.0
        with:
          files: build/${{ matrix.base }}.yml
          push: true

  build-plugins:
    needs: build-base
    strategy:
      matrix:
        desktop: ["kde", "mate", "xfce"]
        plugin: ["NAV_19HIPA", "NAV_20HIPA", "NAV_21HIPA", "NAV_22HIPAK", "NAV_IGAZOL", "OEP_egt_tagallam", "OEP_igenylolap_eu_kartyahoz"]

    runs-on: ubuntu-latest

    env:
      DESKTOP: ${{ matrix.desktop }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and publish the ${{ matrix.plugin }} ${{ matrix.desktop }} image
        uses: docker/bake-action@v2.3.0
        with:
          files: build/plugin/${{ matrix.plugin }}.yml
          push: true

  update-readme:
    needs: [build-base, build-plugins]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: reisingeradam/anyk
          readme-filepath: ./README.en.md
