name: Check for ANYK base and plugin updates

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  update-check:
    strategy:
      matrix:
        target:
          [
            {
              rovidnev: "base",
              source: "https://nav.gov.hu/api/declarationForms/anyk",
              namePrefix: "",
              path: "",
            },
            {
              rovidnev: "OEP_igenylolap_eu_kartyahoz",
              source: "https://hkp.neak.gov.hu/nyomtatvanyok/",
              namePrefix: "",
              path: "plugin/",
            },
            {
              rovidnev: "OEP_egt_tagallam",
              source: "https://hkp.neak.gov.hu/nyomtatvanyok/",
              namePrefix: "",
              path: "plugin/",
            },
            {
              rovidnev: "19HIPA",
              source: "https://nav.gov.hu/api/declarationForms/anyk",
              namePrefix: "NAV_",
              path: "plugin/",
            },
            {
              rovidnev: "20HIPA",
              source: "https://nav.gov.hu/api/declarationForms/anyk",
              namePrefix: "NAV_",
              path: "plugin/",
            },
            {
              rovidnev: "21HIPA",
              source: "https://nav.gov.hu/api/declarationForms/anyk",
              namePrefix: "NAV_",
              path: "plugin/",
            },
            {
              rovidnev: "22HIPAK",
              source: "https://nav.gov.hu/api/declarationForms/anyk",
              namePrefix: "NAV_",
              path: "plugin/",
            },
            {
              rovidnev: "IGAZOL",
              source: "https://nav.gov.hu/api/declarationForms/anyk",
              namePrefix: "NAV_",
              path: "plugin/",
            },
          ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Download repository index
        run: curl -L ${{ matrix.target.source }} -o repository.xml

      - name: Get latest version number for ${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }}
        if: ${{matrix.target.rovidnev == "base" }}
        id: remote_version
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: 'repository.xml'
          xpath: '/adat/keretprogram/verzio'

      - name: Get latest version number for ${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }}
        if: ${{matrix.target.rovidnev != "base" }}
        id: remote_version
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: 'repository.xml'
          # checking 'kategoria' to filter out the help files
          xpath: '/adat/nyomtatvany[kategoria="Template"][rovidnev="${{ matrix.target.rovidnev }}"]/verzio'

      - name: Get current local version number for ${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }}
        id: local_version
        run: echo "version=$(test -f build/${{ matrix.target.path }}${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }}.version && head -n 1 build/${{ matrix.target.path }}${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }}.version || echo 0)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Update ${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }} version file
        if: ${{steps.remote_version.outputs.info > steps.local_version.outputs.version}}
        run: echo ${{ steps.remote_version.outputs.info }} > 'build/${{ matrix.target.path }}${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }}.version'
        shell: bash

      - name: Create pull request
        if: ${{steps.remote_version.outputs.info > steps.local_version.outputs.version}}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update ANYK ${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }} version
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          base: master
          branch: bot/update-anyk-${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }}-version
          delete-branch: true
          title: Update ANYK ${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }} version
          body: Update ANYK ${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }} to the latest version.
          add-paths: build/${{ matrix.target.path }}${{ matrix.target.namePrefix }}${{ matrix.target.rovidnev }}.version
          labels: dependencies

  keepalive-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Update check time
        run: echo $(date -u) > '.github/update-check-time.txt'
        shell: bash

      - name: Push latest check time
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update latest version check time
          branch: bot/keepalive-update-check
          create_branch: true
          push_options: '--force'
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          file_pattern: '.github/update-check-time.txt'
